### ISSUE TITLE
Vue.js example

### ISSUE THREAD

**Issue by giuseppecrj** [alexisvincent/systemjs-hot-reloader#110]
Is there an example project I can reference that utilizes the Vue.js framework with the reloader? I would appreciate any direction. Thank you.

**Comment by jjrv** [comment]
I'm working on such a project template at the moment. It seems to mostly work, but `systemjs-hmr` has just been rewritten so I'm waiting for PR #116 to get merged.

**Comment by alexisvincent** [comment]
@jjrv @giusepperj got a solution?
