### ISSUE TITLE
Major Release

### ISSUE THREAD

**Issue by alexisvincent** [alexisvincent/systemjs-hot-reloader#124]
@capaj If you're happy with the state of the project, do you want to release a major?

**Comment by mpfau** [comment]
@capaj Is there anything that blocks this?

**Comment by capaj** [comment]
@mpfau no, let's hit 1.0.0

**Comment by alexisvincent** [comment]
I'd actually like to hold off until I build backwards compat for __unload and __reload into the hmr rewrite. Then 1.0.0 can be mostly non breaking.
