### ISSUE TITLE
How to do custom loader?

### ISSUE THREAD

**Issue by wegorich** [alexisvincent/systemjs-hot-reloader#143]
I'm trying to do Aurelia.js HMR here [Aurelia HMR](https://github.com/aurelia/hot-module-reload/issues/10).  But can't find the way to setup communication between System HMR and Aurelia loader. 

Would be nice to find example for change subscription. Or how to do custom loader.

**Comment by wegorich** [comment]
Looking to the webpack implementation, they have:

module.hot
module.hot.accept
module.hot.decline
module.hot.dispose

Do we have any similar methods or alternatives to manage the HMR module behavior?
Going to avoid such code in each modules, and make general loader, manage that's stuffs in one place. In custom loader.

"import {module} from '@hot'"
"__unload..."

Does it even possible?

**Comment by wegorich** [comment]
I create a sample to show what am I doing [aurelia-systemjs-loader](https://github.com/wegorich/aurelia-systemjs-loader).

In general I need some how trigger class methods here (loader)[https://github.com/wegorich/aurelia-systemjs-loader/blob/master/src/lib/aurelia-systemjs-loader.js#L101-L111] for example.

**Comment by alexisvincent** [comment]
Lets jump on an instant messenger. One moment.

**Comment by alexisvincent** [comment]
you should have received an invite to the gitter room alexisvincent/systemjs-hmr

**Comment by wegorich** [comment]
So custom loader for systemjs doing via plugins: [documentation how to](https://github.com/systemjs/systemjs/blob/master/docs/creating-plugins.md), [example for vue](https://github.com/vuejs/systemjs-plugin-vue)

it solves my issues with systemjs
