### ISSUE TITLE
Discussion: Integration into jspm core

### ISSUE THREAD

**Issue by guybedford** [alexisvincent/systemjs-hot-reloader#17]
I'd like to propose we bring this project to all users of jspm as part of the 0.17 release, and wanted to get feedback first before considering any further.

The goal here would be to make hot reloading such a simple feature to include that users don't even need to think about it, and for it to be a natural part of the development experience in jspm.

The existing structure of these projects would bundle up quite nicely if we add `chokidar-socket-emitter` as a dependency of jspm itself, and then optionally install the `capaj/jspm-hot-reloader` project when hot reloading is attempted as a devDependency of the project, just like we install the transpilers currently.

Then the workflow here might work something like:

```
jspm hotreload
Watching for file changes on socket 1234.
```

A trend in jspm is the concept of configuration management being handled automatically. It would be even nicer if we can get the HTML and config overheads down to zero, so users don't even need to check the readme.

To reach such a config-less install I'm tempted to create a new property in SystemJS - `System.config({ init: ['jspm-hot-reloader'] })` to allow specifying modules which should be loaded and block all other `System.import` calls in the process. This way, we needn't even ask the user to edit their html to support hot reloading, and can just add the loader to their config file.

The remaining configuration problem then is just how to select the port and host, but these could even be properties available on the `System` object itself in the browser - `System.hotloader.port`, `System.hotloader.host` say, allowing the hot reloader import to be self-initializing to support such a configless workflow.

There will likely also be a special `jspm.dev.js` config file in future, which may then handle the `localhost` check nicely as well, but that is yet to be determined.

We'd still then enforce that users should run their own HTTP server though, which I think would make sense to avoid that can of worms.

@capaj please let me know your thoughts on the above, and if you'd be open to these ideas. From your perspective, the management of the project would remain roughly the same, it would just get a wider audience. I think this project is critical to ensuring jspm can provide a decent development experience, and am really grateful for your picking this up.

**Comment by guybedford** [comment]
Actually I don't think I could pass off the opportunity to call this `jspm hot`....

**Comment by capaj** [comment]
@guybedford great idea! I mean there are few unit tests which I need to implement before I can allow this to be distributed to regular JSPM users, but otherwise everything you propose is well thought through.

I have even made you a collaborator in case you need to merge in some PR/

Totally agree with the http server, the overhead in JSPM userland is so small it doesn't have any benefits.

**Comment by guybedford** [comment]
Excellent, thank you for being open to this! I will aim to start working on the integration on the 0.17 jspm branch.

**Comment by capaj** [comment]
@guybedford it must have a API method as well-so that you can start up chokidar-socket-emitter programatically:
```
System.hot()  // would just call chokidar-socket-emitter with the appropriate port from System config right?
```

**Comment by capaj** [comment]
@guybedford calling the command for hot reloading just 'hot' is certainly is easier to type and remember than `jspm hotreload`

**Comment by guybedford** [comment]
It may make sense to provide two entry points. Perhaps something like:

* `System.import('capaj/jspm-hot-reloader')` where the main entry point does self-initialization
* Documented `System.import('capaj/jspm-hot-reloader/api')` say, which provides fine-grained initialization control.

**Comment by capaj** [comment]
@guybedford which default port? 8080 is a typical dev web server, so I guess 8079 would be a good candidate for the socket.io backend?

**Comment by guybedford** [comment]
I guess it doesn't matter too much. 5776 is jspm on a keypad, and also not otherwise reserved.

**Comment by veggiemonk** [comment]
Been using it for 2 weeks and I have to say that it is great. 

So :+1: for the integration and for `jspm hot`

I saw how webpack does it and it require a bit of code to make it works if you start from scratch. This approach is really elegant, no change in my code whatsoever. However, I don't fully understand how it works and what it's doing. Sometimes it reload a file that hasn't been changed. So to illustrate the common use cases, a little bit of example and/or documentation would be highly appreciated. 
Of course, if the app is doing async request, it has to reload the whole page anyway, right?

Congratulations to you both, it's great.

@guybedford any roadmap on 0.17 ? I searched a bit but I could not find anything specifically related to 0.17.

**Comment by capaj** [comment]
@veggiemonk well it does traverse the tree of dependencies to the root and deletes everything in it's path.

So if you have three modules, A as root, B is child of A and C is child of B and you change C, all three will reload. There is no way a round that. This seems ineffiecient, but keep in mind that typical app has much more wide dependency tree. So even if you have to reload 5 modules, it is very fast compared to reloading 80 for example.

**Comment by veggiemonk** [comment]
@capaj Thanks so much for the example. It seems quite logical. Although, see #22

**Comment by tyscorp** [comment]
If this were integrated into jspm core, I'd like to see the socket parts extracted out and have JSPM just provide an interface to enable hot reloading a module so the user isn't tied to using a specific socket implementation.

**Comment by peteruithoven** [comment]
@tyscorp But than it would only have the functionality of [chokidar](https://www.npmjs.com/package/chokidar)? 
I think the goal is to make it easier, to have as little config as possible?

**Comment by tcurdt** [comment]
integration would be fantastic

**Comment by alexisvincent** [comment]
@guybedford should we try move this forward at all?

**Comment by alexisvincent** [comment]
Closing, since this is a concern of `systemjs-hmr` for now.
