### ISSUE TITLE
css reloading?

### ISSUE THREAD

**Issue by tcurdt** [alexisvincent/systemjs-hot-reloader#32]
Does the hot-reloader also support reloading of css files? I can see the file changes being emitted - but nothing changes inside the browser.

**Comment by veggiemonk** [comment]
It depends how you import your css files....
Through jspm css loader?

**Comment by manveru** [comment]
I made hot reloading CSS work after being frustrated enough to think of a dirty hack. Please note that you probably need to change the two `replace` calls to suit your own dependencies and structure. I'm really out of time to spend on this, but maybe someone else can transform the hack into a useful PR.

     hotReload (moduleName) {
       const self = this
       const start = new Date().getTime()

       if (moduleName.endsWith(".css")) {
         console.debug(moduleName)
         const importPath = moduleName.replace(
           ".css",
           ".css!http://localhost:8080/jspm_packages/npm/jspm-loader-css@1.0.1-beta1.js"
         ).replace("public/", "http://localhost:8080/")

         System.delete(importPath)
         return System.import(importPath)
       }

       this.modulesJustDeleted = {}  // TODO use weakmap
       return this.getModuleRecord(moduleName).then(module => {

**Comment by capaj** [comment]
@manveru noted

**Comment by tcurdt** [comment]
Ah - so similar to webpack loaders I have to import the css files to turn them into hot-reloadable modules with:

  https://github.com/systemjs/plugin-css

@manveru why is the replace with the explicit loader necessary? and `start` is not even used?

**Comment by capaj** [comment]
@tcurdt start is just there for rough performance numbers. Not needed at all for hot-reloading.

**Comment by manveru** [comment]
@tcurdt i have a replace because loading with just `.css!` didn't work, my `chokidar-socket-emitter` sends file names like `public/styles/foo.css`, but in my source I require them as `../styles/foo.css!`.
as I said it's just a quick hack that I didn't spend a lot of time thinking about, and I'm sure there's a more elegant and reliable way, I just didn't research it because it works for me and the approach is likely wrong anyway.

**Comment by pibi** [comment]
More elegant, but still hackish, way to hot reload css/html, without code changes

```
          let name;
          System.hotReloader.on('change',(_name)=>{name=_name});
          System.hotReloader.once('moduleRecordNotFound', (err) => {
            console.log(name.path, "moduleRecordNotFound, retry on modules");
            var module = Object.keys( System._loader.modules).filter(function (value){return value.match(name.path)});
            if (module) {
              name.path = module[0].substr(module[0].indexOf(name.path))
              onChange(name);
            } else {
              console.log(name.path, "module not found");
            }
          });
```
@capaj it could be more reliable if  'moduleRecordNotFound' emits the original name.

**Comment by CaptainN** [comment]
Where do I apply this hack to get it to work?

**Comment by CaptainN** [comment]
I got it working by using the jspm package linked above (`jspm install css`) and then using this fix in the main index file (modified from the above hack and the jspm hot reloader setup tutorial):

```JavaScript
System.trace = true
System.import('capaj/systemjs-hot-reloader').then(function(HotReloader){
  var hotReloader = new HotReloader.default('rev.dev:9089');  // chokidar-socket-emitter port

  // fix for CSS hot reloading (relies on jspm package `css`)
  var onChange = hotReloader.onFileChanged.bind(hotReloader);
  var name;
  hotReloader.on('change', function (_name) {
    name = _name;
  });
  hotReloader.on('moduleRecordNotFound', function (err) {
    var keys = Object.keys (System._loader.modules);
    var module;
    for (var i = 0, n = keys.length; n > i; i++) {
      var value = keys[i];
      if (value.match(name)) {
        module = keys[i];
      }
    }
    if (module) {
      name = module.substr (module.indexOf (name));
      onChange({path:name});
    } else {
      console.log(name.path, "module not found");
    }
  });
});
System.buildCSS = false;
System.import('assets/stylesheets/main.css!');

System.import('assets/javascripts/main');
```

**Comment by nagitsu** [comment]
The previous approaches were giving me trouble, as the `<link>` tag for the CSS file was being inserted more than once, causing conflicts with all the different versions.

I built a (still-hackish) alternative, which also works for CSS files not imported through the jspm CSS loader:

```javascript
let hotReloader = new HotReloader('http://localhost:5776');
let onChange = hotReloader.onFileChanged.bind(hotReloader);

let name;
hotReloader.on('change', _name => name = _name);

hotReloader.on('moduleRecordNotFound', _ => {
  if (name.endsWith('.css')) {
    // It's a CSS file, build the new <link> tag.
    let newLink = document.createElement('link');
    newLink.type = 'text/css';
    newLink.rel = 'stylesheet';

    let links = document.getElementsByTagName('link');
    for (let link of links) {
      // Find the <link> that holds the CSS file, and replace it with the new node.
      // We add a `#` and random value to force a refresh of the CSS.
      let oldHref = link.href;
      if (oldHref.indexOf('#') != -1) {
        oldHref = oldHref.substr(0, oldHref.indexOf('#'));
      }

      if (oldHref.endsWith(name)) {
        let newHash = Math.round(Math.random() * 1e10);
        let baseUrl = oldHref.substr(0, oldHref.indexOf(name));
        newLink.href = `${baseUrl}${name}#${newHash}`;
        link.parentNode.replaceChild(newLink, link);
      }
    }
  }
});
```

This will create the `<link>` tag manually as it's done on [the CSS plugin](https://github.com/systemjs/plugin-css/blob/master/css.js), adding a hash with a random value to force a refresh of the CSS (will be ignored otherwise).

Note that this will break if the CSS URL is already using a hash value for something.

**Comment by CaptainN** [comment]
How do we make that not hacky?

Perhaps and extension that would automatically scan the DOM for existing links, and add them to be refreshed using the technique above (@nagitsu's technique).

By that I mean, we could loop over all the `link` elements and register them at startup. Then use the `moduleRecordNotFound` hook as a simple filter (unless there is a better - not hacky - way to plug in).

At least then it'd be encapsulated, if still hacky.

**Comment by shovemedia** [comment]
I got this to work without *too* much hackery. See comment here:
https://github.com/systemjs/plugin-css/pull/73#issuecomment-226945681

**Comment by guybedford** [comment]
@shovemedia nice, if you think there is something that could be added to this project or the css plugin to provide this support more naturally, contributions would be really welcome.

**Comment by divramod** [comment]
can anyone please give me a link with a running example, which combines hmr + css reloding?

**Comment by alexisvincent** [comment]
@guybedford, would you be able to add an __unload export to the css plugin as we discussed?

**Comment by alexisvincent** [comment]
Tracking here -> https://github.com/alexisvincent/systemjs-hot-reloader/issues/131
