### ISSUE TITLE
Install instructions for SystemJS without jspm

### ISSUE THREAD

**Issue by guybedford** [alexisvincent/systemjs-hot-reloader#36]
It would be great to have a small section for non-jspm users on how to get set up with this project.

Then this could be provided as the main workflow tool for developing on SystemJS. That would potentially bring this project to the Angular 2 ecosystem, where native SystemJS without jspm seems to be a trend.

**Comment by capaj** [comment]
Angular2 ecosystem uses which package manager? NPM? Bower? Or none?

**Comment by guybedford** [comment]
npm I believe.

**Comment by mpfau** [comment]
This is how my `system.config.js` looks like:

    paths: {
        "npm:*": "node_modules/*"
    },

    map: {
        "systemjs-hot-reloader": "npm:systemjs-hot-reloader/hot-reloader.js",
        "debug": "npm:debug",
    },

    packages: {
        "systemjs-hot-reloader": {
            map: {
                "socket.io-client": "npm:socket.io-client/socket.io.js",
                "weakee": "npm:weakee/weakee.js",
            },
        },
        "debug": {
            main: "browser",
            defaultExtension: "js",
            map: {
                "ms": "npm:ms/index.js"
            }
        },
    }

**Comment by jjrv** [comment]
I've gotten the hot reloader working with just SystemJS and no transpiler. Here's a link to the repo: https://github.com/charto/charto-map-frontend/tree/fdac5c6f33c75331c29994236ab2a5895ece12eb

It uses a small tool called [`cbuild`](https://github.com/charto/cbuild) to help `systemjs-builder` understand the `browser` field in `package.json` and autogenerate config.js entries.

That means my install script runs:
```bash
cbuild -s node_modules/systemjs-hot-reloader/hot-reloader.js -o reloader-bundle.js -C config-reloader.js
```

It generates a bundle `reloader-bundle.js` that loads fine in the browser without any transpiler, and a file `config-reloader.js` with the following contents:

```js
System.config({
    map: {
        "debug": "node_modules/debug/browser.js",
        "weakee": "node_modules/weakee/weakee.js",
        "socket.io-client": "node_modules/socket.io-client/lib/index.js",
        "ms": "node_modules/ms/index.js",
        "socket.io-parser": "node_modules/socket.io-parser/index.js",
        "component-emitter": "node_modules/engine.io-client/node_modules/component-emitter/index.js",
        "isarray": "node_modules/isarray/index.js",
        "json3": "node_modules/json3/lib/json3.js",
        "parseuri": "node_modules/parseuri/index.js",
        "component-bind": "node_modules/component-bind/index.js",
        "to-array": "node_modules/to-array/index.js",
        "has-binary": "node_modules/engine.io-parser/node_modules/has-binary/index.js",
        "engine.io-client": "node_modules/engine.io-client/index.js",
        "indexof": "node_modules/indexof/index.js",
        "backo2": "node_modules/backo2/index.js",
        "engine.io-parser": "node_modules/engine.io-parser/lib/browser.js",
        "parsejson": "node_modules/parsejson/index.js",
        "arraybuffer.slice": "node_modules/arraybuffer.slice/index.js",
        "parseqs": "node_modules/parseqs/index.js",
        "base64-arraybuffer": "node_modules/base64-arraybuffer/lib/base64-arraybuffer.js",
        "utf8": "node_modules/utf8/utf8.js",
        "after": "node_modules/after/index.js",
        "blob": "node_modules/blob/index.js",
        "xmlhttprequest-ssl": "node_modules/engine.io-client/lib/xmlhttprequest.js",
        "ws": "node_modules/browser-resolve/empty.js",
        "has-cors": "node_modules/has-cors/index.js",
        "yeast": "node_modules/yeast/index.js",
        "component-inherit": "node_modules/component-inherit/index.js"
    },
    packages: {
        ".": {
            map: {
                "./node_modules/engine.io-client/lib.js": "./node_modules/engine.io-client/lib/index.js",
                "./node_modules/engine.io-client/lib/transports.js": "./node_modules/engine.io-client/lib/transports/index.js"
            }
        }
    }
});
```

**Comment by jonricaurte** [comment]
This would be awesome!

**Comment by alexisvincent** [comment]
Instructions in repo don't depend on JSPM.
