### ISSUE TITLE
add disable method for disabling hot reloader

### ISSUE THREAD

**Issue by capaj** [alexisvincent/systemjs-hot-reloader#38]

**Comment by guybedford** [comment]
@geelen used a `__hotReload: false` flag for this if I recall correctly.

**Comment by peteruithoven** [comment]
Another hack that forces a regular refresh instead of a hot reload: 
``` javascript 
export function __unload(deletedModule) {
  window.location = window.location;
}
```
I use this when I'm using Tape.

**Comment by capaj** [comment]
@peteruithoven clever, but I really want hot reloader to ignore every event

@guybedford I just came across a use case, where I made lots of CSS changes inside chrome dev tools and wanted to keep them there exactly like that while I do changes into the app. Probably not that common, but could be useful in other cases

**Comment by guybedford** [comment]
Ah right, sorry for the misinterpretation. So a `hotReloader.pause()` rather?

**Comment by capaj** [comment]
@guybedford that seems like a better name, will implement that

**Comment by guybedford** [comment]
Is it not the watcher you want to pause here though rather?

**Comment by capaj** [comment]
@guybedford  no, I then I couldn't work in other browser windows with hot reload

**Comment by guybedford** [comment]
Ah right I see!

Also to update it has turned out I won't have time to integrate hot reloading into core for this 0.17 alpha currently, but it will definitely happen at some point. In the mean time I'll make sure to include the project in the docs though to get users on it.

**Comment by capaj** [comment]
@guybedford no probs, I think modular development is good enough. Don't lose time on hot reloading, give us babel 6 and rollup. Those two features will be big enough for 0.17.0 release.

**Comment by alexisvincent** [comment]
Closing for now. Will implement if someone else asks for this.
