### ISSUE TITLE
I get the same error as in #42

### ISSUE THREAD

**Issue by jonahlau** [alexisvincent/systemjs-hot-reloader#57]
This issue was marked as closed in #42 , but I'm still experiencing the same error even when I have  jspm v0.17.0 or v0.16.24 with hot reloader v0.5.5

I'm only able to get it running with hot-reloader 0.5.5 with jspm 0.16.19.

**Comment by alexisvincent** [comment]
@jonahlau Still an issue for you?

**Comment by alexisvincent** [comment]
The codebase that this error occurred in no longer exists. Closing
