### ISSUE TITLE
Running in web worker

### ISSUE THREAD

**Issue by eesdil** [alexisvincent/systemjs-hot-reloader#60]
The debug is not working under web worker in angular2 it is throwing error.
`Error: The NodeJS "child_process" module is not available in the browser`

If the old console.debug is placed back it is working. 

Also needed to remove the `window.onerror` as window is not present.

**Comment by alexisvincent** [comment]
Still an issue?

**Comment by alexisvincent** [comment]
Closing this since its inactive, feel free to reopen if this is still an issue.
