### ISSUE TITLE
Problem with plugin-typescript when switching typeCheck to true or "strict"

### ISSUE THREAD

**Issue by svi3c** [alexisvincent/systemjs-hot-reloader#87]
The reloader works for me using plugin-typescript as long as I do not tell it to run type checking.
When I turn it on via

``` javascript
typescriptOptions: {
  "typeCheck": "strict"
}
```

I get a cross-origin request error in the browser, since it somehow resolves the plugin url as a file path:

```
XMLHttpRequest cannot load file://[project-root]/jspm_packages/github/frankwallis/plugin-typescript@4.0.10/plugin.js. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.
```

**Comment by alexisvincent** [comment]
@svi3c Still an issue?

**Comment by alexisvincent** [comment]
@svi3c If still an issue, please reopen. Theres a new codebase and so chances of this issue creating few are low.
