### ISSUE TITLE
Hot-reloading with plugin-text via meta config does not work in JSPM 0.17 beta

### ISSUE THREAD

**Issue by svi3c** [alexisvincent/systemjs-hot-reloader#91]
I would like to get hot reloading work with https://github.com/systemjs/plugin-text for my Angular 2 component templates.
To achieve this I would prefer using the config meta aproach.
In my project https://github.com/flaviait/ng2-jspm-template/tree/ng2-jspm-template-9 I've tried the following configuration:

```
packages: {
  'src': {
    'main': 'main',
    'defaultExtension': 'ts',
    'meta': {
      '*.ts': {
        'loader': 'plugin-typescript'
      },
      '*.scss': {
        'loader': 'scss'
      },
      '*.html': {
        'loader': 'text'
      }
    }
  }
}
```

This works for utilizing plugin-text, but when I do a change, no module reload is triggered.
The https://github.com/KevCJones/plugin-scss works very well with module reloads.
Any ideas?

**Comment by capaj** [comment]
@svi3c there are currently two opened PRs related to html template reloading: https://github.com/capaj/systemjs-hot-reloader/pull/85
https://github.com/capaj/systemjs-hot-reloader/pull/73

Do you think any of them could help to make this work?

**Comment by svi3c** [comment]
@capaj At first glance I cannot tell you for sure, but I can have a deeper look at these PRs tonight or tomorrow in the morning.

**Comment by svi3c** [comment]
I applied both PRs, but none of them fixed the problem.
I found out that there are two issues with the module reloading of the html files:

1) the module is not found when using the meta information. A fix would be to add this snippet at [Line 158](https://github.com/herdemir/systemjs-hot-reloader/blob/023c9d50d119ab3a918151d4a5f9ab7039219824/hot-reloader.js#L158):
```javascript
if(!module) {
  moduleImportName = System.normalizeSync(moduleName)
  module = System.loads[moduleImportName]
}
```

2) When the module is found with the fix in 1), no importers are present on the module. I'm not sure why.

**Comment by capaj** [comment]
@svi3c should be fixed in 0.5.9, if not, let me know.

**Comment by svi3c** [comment]
Hi @capaj, I updated the packages and reloaded the entry module directly after load in https://github.com/flaviait/ng2-jspm-template/commit/a38f5d3833f0c205425ce19ea23edf027e6fca18.
Unfortunately it does not work for me.

**Comment by capaj** [comment]
@svi3c thanks, will clone your repo and try it myself over the weekend.

**Comment by j-walker23** [comment]
@svi3c it looks like this is fixed in the latest version i just pulled.
@capaj thanks! you are the man. Frontend dev just keeps getting cooler every day.

**Comment by worldspawn** [comment]
meta option i put in doesn't seem to have had any effect
```
  meta: {
    "*.html": {
      "loader": "text"
    },
    "*.scss": {
      "loader": "scss"
    }
  },
```

My understanding is i should now be able to import matching file without a `!` suffix. instead i get 404 for `app.html.js` when doing `import template from './app.html';`

**Comment by DorianGrey** [comment]
Even with the latest version, reloading template files does not really work in our case - I've just tested it with this branch: https://github.com/flaviait/ng2-jspm-template/tree/ts2-templates
Changes appear to be recognized, but are not applied.

**Comment by thalen** [comment]
I have a solution for this, what I do is to set up the hot reloader first after the source has been imported.

<ol>
<li>
Load the hot reloader service
</li>
<li>
After the hot reloader has been loaded, but not started, import the application source
</li>
<li>
Now start up the hot reloader
</li>
</ol>

<pre>
    System.trace = true;
    readyForMainLoad = System.import('systemjs-hot-reloader').then(function(HotReloader){
        hotReloaderService = HotReloader;
    });

    Promise.resolve(readyForMainLoad).then(function() {
        System.import('./app/styles/main.scss!');
        System.import("app").then(function() {
            console.log("running");
            hr = new hotReloaderService.default('http://localhost:9089');
        });
    });
</pre>

After this, the component gets updated after a change in the template.
I'm using JSPM 0.17.0-beta.22 and systemjs-hot-reloader 0.6.0

**Comment by born2net** [comment]
but in my case, I am using angular2, and there are over 100+ separate html templates / css style files (per each component).

Importing all of them that way is not feasible, unless you have another idea?

regards

Sean

**Comment by thalen** [comment]
I'm also using angular2 but just got started, and I only have a small number of components so far. So I have no solution for any scaling issues with jspm and angular2.

**Comment by born2net** [comment]
ya I understand...
by the way, checkout:
Angular 2 Kitchen sink: http://ng2.javascriptninja.io
and source@ https://github.com/born2net/ng2Boilerplate

you will see that I load lots of templates and css files, so ya... still an issue.
regards

Regards,

Sean

**Comment by alexisvincent** [comment]
@born2net Any chance you could submit a failing test case to `systemjs-hmr`

**Comment by alexisvincent** [comment]
Tracking in #131
