### ISSUE TITLE
Path issue

### ISSUE THREAD

**Issue by nickbalestra** [alexisvincent/systemjs-hot-reloader#96]
Hello, somehow i cannot make the hot reloader work with a nested folder structure. 
I'm probably missing something here

I created a repo with the 2 structures:
- [working structure](https://github.com/nickbalestra/systemjs-hot-reloader-issue/tree/master): just run the server and edit the client.js -> hot reloader properly work
-  [not-working structure](https://github.com/nickbalestra/systemjs-hot-reloader-issue/tree/broken): just run the server and edit the client.js -> hot reloader doesn't work anymore.

any help will be appreciated!

**Comment by alexisvincent** [comment]
@nickbalestra Can you checkout the v1.0.0 release and see if you still have this issue.

**Comment by alexisvincent** [comment]
Note, chokidar will emit events relative to the dir its running in. `systemjs-hot-reloader` expects to receive events relative to the `baseURL`. I think that was your issue. Closing for now. If this is still an issue, feel free to reopen.
